language: python
    addons:
      postgresql: 10.10
      apt:
        packages:
          - postgresql-10.10-postgis-2.5
    python:
      - "3.6"
    services:
      - postgresql
    env:
      -$DEBUG
      -$DATABASE_DEFAULT
      -$SECRET_KEY
      -$ALLOWED_HOST
    install:
      - pip install -r requirements.txt
    before_script:
      - psql -c 'create database gis_portfolio_test; create extension postgis;' -U postgres
    script:
      - python manage.py test